// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFnpfjpLcNfzXPo5WX0MS7mU72G8I8MM',
    appId: '1:864519018143:web:7d6f9b266c236215b534aa',
    messagingSenderId: '864519018143',
    projectId: 'jms-app-39e59',
    authDomain: 'jms-app-39e59.firebaseapp.com',
    storageBucket: 'jms-app-39e59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYy6VqWU6pFbaHiUhfhS77z-8cJyGStpc',
    appId: '1:864519018143:android:c83c1541c061fdc3b534aa',
    messagingSenderId: '864519018143',
    projectId: 'jms-app-39e59',
    storageBucket: 'jms-app-39e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nr-XtPJoa4S0HKHUc-Bp-x4SqMOhUJE',
    appId: '1:864519018143:ios:e97a146b2789d7beb534aa',
    messagingSenderId: '864519018143',
    projectId: 'jms-app-39e59',
    storageBucket: 'jms-app-39e59.firebasestorage.app',
    iosBundleId: 'com.jal.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nr-XtPJoa4S0HKHUc-Bp-x4SqMOhUJE',
    appId: '1:864519018143:ios:67bb0d5e45a94d38b534aa',
    messagingSenderId: '864519018143',
    projectId: 'jms-app-39e59',
    storageBucket: 'jms-app-39e59.firebasestorage.app',
    iosBundleId: 'com.example.jms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFnpfjpLcNfzXPo5WX0MS7mU72G8I8MM',
    appId: '1:864519018143:web:1b25984c580a40d8b534aa',
    messagingSenderId: '864519018143',
    projectId: 'jms-app-39e59',
    authDomain: 'jms-app-39e59.firebaseapp.com',
    storageBucket: 'jms-app-39e59.firebasestorage.app',
  );
}
